<?php

namespace AppBundle\Repository;

/**
 * ProjectBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
