<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBy($args, $isQuery = false) {
        $q = '';
        $array = [];

        $sql = "
                SELECT
                    p
                FROM AppBundle:Project p
                WHERE
                    1 = 1
                    $q
                ORDER BY
                    p.createAt DESC
            ";

        $query = $this->getEntityManager()
            ->createQuery($sql)
            ->setParameters($array);

        if (isset($args['page']) && $args['page'] > 0 && isset($args['limit']) && $args['limit'] > 0) {
            $first = ($args['page'] - 1) * $args['limit'];
            $query->setFirstResult($first);
            $query->setMaxResults($args['limit']);
        }

        if ($isQuery == true)
            return $query;
        return $query->getResult();
    }

    public function countBy($args) {
        $q = '';
        $array = [];

        $sql = "
                SELECT
                    COUNT(p)
                FROM AppBundle:Project p
                WHERE
                    1 = 1
                    $q
            ";

        return $this->getEntityManager()
            ->createQuery($sql)
            ->setParameters($array)
            ->getSingleScalarResult();
    }
}
